book_review/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'book_review'
urlpatterns = [
    # Index page and list of anticipated books.
    path('', views.IndexListView.as_view(), name='index'),
    # List of published books ordered according to provided url argument.
    path('published_books/', views.BooksListView.as_view(), name='books_list'),

    # Book detail page.
    re_path(r'^book/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),

    # Create, edit and delete review pages.
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/add/$', login_required(views.ReviewCreateView.as_view()), name='add_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/edit/$', login_required(views.ReviewUpdateView.as_view()), name='edit_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/delete/$', login_required(views.ReviewDeleteView.as_view()), name='delete_review'),

    # User reviews page.
    path('my_reviews/', login_required(views.MyReviewsListView.as_view()), name='my_reviews'),

    # Search results page.
    path('search/', views.SearchListView.as_view(), name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

br/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'br'
urlpatterns = [
    # Index page.
    path('', views.IndexListView.as_view(), name='index'),
    # Books lists pages.
    re_path(r'^(?P<sort_type>(recent|popular|best_rated))/$', views.BooksListView.as_view(), name='books_list'),
    # Book detail page.
    re_path(r'^book/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),
    # Create, edit and delete review pages.
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/add/$', login_required(views.ReviewCreateView.as_view()), name='add_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/edit/$', login_required(views.ReviewUpdateView.as_view()), name='edit_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/delete/$', login_required(views.ReviewDeleteView.as_view()), name='delete_review'),
    # My reviews page.
    path('my_reviews/', login_required(views.MyReviewsListView.as_view()), name='my_reviews'),
    # Search results page.
    path('search/', views.SearchListView.as_view(), name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),
    # book_review urls
    path('', include('book_review.urls')),
    # users urls
    path('', include('users.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve
    from django.views.decorators.cache import never_cache
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # маршрут для обработки выгруженных файлов
else: # only for heroku , if deploy + nginx/apache need refactor
    from django.views.static import serve as serve
    urlpatterns.extend([
        url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),   
    ])
    

book_review/models.py
import datetime

from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

from .custom.constants import RATINGS


def get_sentinel_user():
    """
    If user is deleted replaces 'owner' field in Review model with 'deleted user' object.
    """
    return get_user_model().objects.get_or_create(username='deleted user')[0]


class Author(models.Model):
    """
    Book author model.
    """
    first_name = models.CharField(max_length=50)
    patronymic = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    born = models.DateField(
        help_text='YYYY-MM-DD',
        validators=[MaxValueValidator(limit_value=datetime.date.today)]
    )

    class Meta:
        unique_together = ['first_name', 'patronymic', 'last_name', 'born']
        ordering = ['first_name']

    def __str__(self):
        """
        String representation is an author's full name.
        """
        parts = [self.first_name, self.last_name]
        if self.patronymic:
            parts.insert(1, self.patronymic)

        return " ".join(parts)


class Genre(models.Model):
    """
    Book genre model.
    """
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    Book model.
    """
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100, blank=True)
    # Book might have multiple authors, so many-to-many relationship is used.
    authors = models.ManyToManyField(Author)
    genres = models.ManyToManyField(Genre)
    language = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    # Not limiting pub_date max value by today in case of anticipated books.
    pub_date = models.DateField(help_text='YYYY-MM-DD')
    description = models.TextField(max_length=1024, blank=True)
    full_img = models.ImageField(upload_to='img/book_img/full/', default='img/book_img/full/default-book-full.jpg')
    small_img = models.ImageField(upload_to='img/book_img/small/', default='img/book_img/small/default-book-small.jpg')
    pages = models.PositiveIntegerField(null=True, blank=True)
    slug = models.SlugField(max_length=80)

    class Meta:
        unique_together = ['title', 'pub_date']
        ordering = ['title']

    def is_published(self):
        """
        Returns True if book is already published.
        """
        return self.pub_date <= datetime.date.today()

    def get_absolute_url(self):
        # Using slug only is not safe enough since different books may have identical titles.
        # Using id only is not giving informative url for user,
        # So slug and id are used together.
        return reverse('book_review:book', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def __str__(self):
        return self.title


class Review(models.Model):
    """
    Review model.
    """
    title = models.CharField(max_length=60)
    # One review can only refer to one book.
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    text = models.TextField(max_length=8192)
    rating = models.IntegerField(choices=RATINGS)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET(get_sentinel_user)
    )
    pub_date = models.DateField(auto_now_add=True)

    class Meta:
        # Put unique constraint on book and owner fields,
        # since each user may only have 1 review on each book.
        unique_together = ['book', 'owner']

    def __str__(self):
        return self.title

book_review/forms.py
from django import forms


class SearchForm(forms.Form):
    """
    Sends data to SearchListView via GET method.
    """
    q = forms.CharField(max_length=50, label='', widget=forms.TextInput(attrs={
        'placeholder': 'Book, author, genre, year...',
        'class': 'form-control search-form',
    }),
                        )

book_review/views.py
import datetime
from itertools import chain

from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.http import Http404
from urllib3 import HTTPResponse

from .models import Book, Review
from .custom.annotations import annotated_books
from .custom.search import search
from .forms import SearchForm
from .custom.constants import BOOKS_PER_PAGE, REVIEWS_PER_PAGE, SEARCH_CATEGORIES

# from django.http import HttpResponse # test plug


class IndexListView(generic.list.ListView):
    """
    Return list of anticipated books ordered by book publication date and title.
    """
    template_name = 'general/index.html'
    context_object_name = 'anticipated_books'
    paginate_by = BOOKS_PER_PAGE

    def get_queryset(self):
        today = datetime.date.today()
        anticipated_books = annotated_books.filter(pub_date__gt=today)
        return anticipated_books.order_by('pub_date', 'title')


class BooksListView(generic.list.ListView):
    """
    Return list of published books ordered according to provided url argument.
    'recent', 'popular' or 'best_rated' argument values are possible.
    Different argument value leads to 404.
    """
    template_name = 'books/books_list.html'
    context_object_name = 'books'
    paginate_by = BOOKS_PER_PAGE

    def get(self, *args, **kwargs):
        if self.request.GET.get('order') is None:
            return redirect(reverse('book_review:books_list') + '?order=recent')
        return super().get(*args, **kwargs)

    def get_queryset(self):
        today = datetime.date.today()
        published_books = annotated_books.filter(pub_date__lte=today)
        order_dict = {
            'recent': '-pub_date',
            'popular': '-num_reviews',
            'best_rated': '-avg_rating',
        }
        order_key = self.request.GET.get('order')
        order_value = order_dict.get(order_key)
        if order_value is None:
            raise Http404
        return published_books.order_by(order_value, 'title')


class BookDetailView(generic.detail.DetailView):
    """
    Return a particular book and list of reviews for it.
    Reviews are ordered by review publication date.
    Authenticated user who already has review on requested book
    will always see his review on the top of the list regardless of the date.
    """
    model = Book
    queryset = annotated_books
    query_pk_and_slug = True
    template_name = 'books/book_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = Review.objects.filter(book=context.get('book')).order_by('-pub_date')
        user = self.request.user if self.request.user.is_authenticated else None
        user_review = reviews.filter(owner=user).first()

        if user_review:
            other_reviews = reviews.exclude(owner=user)
            reviews = list(chain((user_review, ), other_reviews))

        paginator = Paginator(reviews, REVIEWS_PER_PAGE)
        page_number = self.request.GET.get('page', '1')
        page_obj = paginator.get_page(page_number)

        context.update({
            'paginator': paginator,
            'page_obj': page_obj,
            'is_paginated': True,
            'reviews': reviews,
        })
        return context


class ReviewCreateView(generic.edit.CreateView):
    """
    Create new review on a book.
    User may have at most one review for each book.
    If user already has review for requested book or book is not published yet,
    user will be redirected to book detail page.
    """
    model = Review
    fields = ['rating', 'title', 'text']
    template_name = 'reviews/add_review.html'

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        book_reviews = book.review_set.all()
        users_already_reviewed = User.objects.filter(review__in=book_reviews)

        if not book.is_published() or request.user in users_already_reviewed:
            return redirect(book)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book,
        })
        return context

    def form_valid(self, form):
        new_review = form.save(commit=False)
        new_review.owner = self.request.user
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        new_review.book = book
        return super().form_valid(form)

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()


class ReviewUpdateView(generic.edit.UpdateView):
    """
    Update authenticated user's review for a particular book.
    """
    fields = ['rating', 'title', 'text']
    template_name = 'reviews/edit_review.html'

    def get_object(self, queryset=None):
        # Get review by its book and owner fields since review.owner and review.book have unique_together constraint.
        # Benefit is a simple url without review id, for example, '/review/9-war-and-peace/edit/'.
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        review = get_object_or_404(Review, book=book, owner=self.request.user)
        return review

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book
        })
        return context


class ReviewDeleteView(generic.edit.DeleteView):
    """
    Delete authenticated user's review for a particular book.
    """
    template_name = 'reviews/delete_review.html'
    query_pk_and_slug = True

    def get_object(self, queryset=None):
        # Get review by its book and owner fields since review.owner and review.book have unique_together constraint.
        # Benefit is a simple url without review id, for example, '/review/9-war-and-peace/delete/'.
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        review = get_object_or_404(Review, book=book, owner=self.request.user)
        return review

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book
        })
        return context

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()


class MyReviewsListView(generic.list.ListView):
    """
    Return a list of all reviews written by a user.
    Reviews are ordered by review publication date.
    """
    template_name = 'reviews/my_reviews.html'
    context_object_name = 'my_reviews'
    paginate_by = REVIEWS_PER_PAGE

    def get_queryset(self):
        return Review.objects.filter(owner=self.request.user).order_by('-pub_date', 'title')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SearchListView(generic.list.ListView):
    """
    Return a list of books found by request.
    'q' is a name of the variable that points to query string.
    """
    template_name = 'search/search.html'
    context_object_name = 'results'
    paginate_by = BOOKS_PER_PAGE

    def get(self, request, *args, **kwargs):
        form = SearchForm(data=request.GET)

        if form.is_valid():
            return super().get(request, *args, **kwargs)
        elif form.data.get('q') is None:
            return render(request, 'search/empty_search_request.html')
        else:
            return render(request, 'search/wrong_search_request.html')

    def get_queryset(self):
        q = self.request.GET.get('q')
        category = self.request.GET.get('category')
        results = search(q, category)
        return results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'q': self.request.GET.get('q'),
            'category': self.request.GET.get('category'),
            'SEARCH_CATEGORIES': SEARCH_CATEGORIES,
        })
        return context

book_review/templates/reviews/add_review.html
{%  extends 'general/base.html' %}

{% block page_header %}
    <div class="pb-1 mb-4 border-bottom">
        <h2>New review on «{{book.title}}»</h2>
    </div>
{% endblock page_header %}

{% block content %}
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'book_review:add_review' book.id book.slug %}">
        {% csrf_token %}
        <div class="col-md-1 mb-0">
            {{ form.rating|as_crispy_field }}
        </div>
        {{ form.title|as_crispy_field }}
        {{ form.text|as_crispy_field }}
        <button class="btn btn-color" name="submit">Add review</button>
    </form>
{% endblock content %}

book_review/templates/reviews/delete_review.html
{%  extends 'general/base.html' %}

{% block page_header %}
    <div class="pb-1 mb-4 border-bottom">
        <h2>Review delete page</h2>
    </div>
{% endblock page_header %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete review on «{{book.title}}»?</p>
        <button class='btn btn-color' name="submit">Yes, delete review</button>
    </form>

{% endblock content %}

book_review/templates/reviews/edit_review.html
{%  extends 'general/base.html' %}

{% block page_header %}
    <div class="pb-1 mb-4 border-bottom">
        <h2>Edit my review on «{{book.title}}»</h2>
    </div>
{% endblock page_header %}
{% block content %}
    {% load crispy_forms_tags %}
    <form method="post" action="{% url 'book_review:edit_review' book.id book.slug %}">
        {% csrf_token %}
        <div class="col-md-1 mb-0">
            {{ form.rating|as_crispy_field }}
        </div>
        {{ form.title|as_crispy_field }}
        {{ form.text|as_crispy_field }}
        <button class="btn btn-color" name="submit">Save changes</button>
    </form>
{% endblock content %}

book_review/templates/reviews/my_reviews.html
{% extends 'general/base.html' %}
{% load static %}

{% block page_header %}
    <div class="pb-1 mb-4 border-bottom">
        <h2>My reviews</h2>
    </div>
{% endblock page_header %}

{% block content %}
    {% if my_reviews %}
        {% for review in my_reviews %}
            {% include 'reviews/review_card.html' %}
        {% endfor %}
    {% else %}
        <h4>I haven't written reviews yet.</h4>
        <div class="d-flex justify-content-center p-2">
            <img src="{% static 'custom/img/my_reviews.jpg' %}" class="img-fluid" style="max-height: 345px;" alt="">
        </div>
    {% endif %}
    {% include 'general/pagination.html' %}
{% endblock content %}

book_review/templates/reviews/review_card.html
<div class="card mb-3">

    <div class="card-header">

        <div class="row g-0">

            <div class="col-md">
                <p class="mb-0 text-muted">
                    {% if request.path == '/my_reviews/' %}
                        {{ review.pub_date }} | Review on <span class="text-nowrap">
                            <a class="review-link" href="{{ review.book.get_absolute_url }}">{{ review.book.title }}</a>
                        </span>
                    {% else %}
                        {{ review.pub_date }} | {{ review.owner|title }}
                    {% endif %}
                </p>
            </div>

            <div class="col-auto">
                {% if review.owner == request.user %}
                    <p class="mb-0">
                        <span class="text-nowrap">
                            <a class="review-link" href="{% url 'book_review:edit_review' review.book.id review.book.slug %}">Edit review</a> |
                            <a class="review-link" href="{% url 'book_review:delete_review' review.book.id review.book.slug %}">Delete review</a>
                        </span>
                    </p>
                {% endif %}
            </div>

        </div>

    </div>

    <div class="card-body">
        <h5 class="card-title">{{review.title}}</h5>
        <p class="card-text">Rating: {{ review.rating }}/5</p>
        <div class="card-text">
            {% if review.text|length > 700 %}
                <p>{{ review.text|slice:':700' }}<span id="dots{{ review.id }}">...</span><span class="textContinuation" id="more{{ review.id }}">{{ review.text|slice:'700:'}}</span>
                    <a class="text-nowrap orange-link" onclick="myFunction({{ review.id }})" id="myBtn{{ review.id }}">Read more</a>
                </p>
            {% else %}
                <p>{{ review.text }}</p>
            {% endif %}
        </div>
    </div>

</div>