book_review/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from . import views

app_name = 'book_review'
urlpatterns = [
    # Index page and list of anticipated books.
    path('', views.IndexListView.as_view(), name='index'),
    # List of published books ordered according to provided url argument.
    path('published_books/', views.BooksListView.as_view(), name='books_list'),

    # Book detail page.
    re_path(r'^book/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),

    # Create, edit and delete review pages.
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/add/$', login_required(views.ReviewCreateView.as_view()), name='add_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/edit/$', login_required(views.ReviewUpdateView.as_view()), name='edit_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/delete/$', login_required(views.ReviewDeleteView.as_view()), name='delete_review'),

    # User reviews page.
    path('my_reviews/', login_required(views.MyReviewsListView.as_view()), name='my_reviews'),

    # Search results page.
    path('search/', views.SearchListView.as_view(), name='search'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

br/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required
from . import views

app_name = 'br'
urlpatterns = [
    # Index page.
    path('', views.IndexListView.as_view(), name='index'),
    # Books lists pages.
    re_path(r'^(?P<sort_type>(recent|popular|best_rated))/$', views.BooksListView.as_view(), name='books_list'),
    # Book detail page.
    re_path(r'^book/(?P<pk>\d+)-(?P<slug>[\w-]+)/$', views.BookDetailView.as_view(), name='book'),
    # Create, edit and delete review pages.
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/add/$', login_required(views.ReviewCreateView.as_view()), name='add_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/edit/$', login_required(views.ReviewUpdateView.as_view()), name='edit_review'),
    re_path(r'^review/(?P<pk>\d+)-(?P<slug>[\w-]+)/delete/$', login_required(views.ReviewDeleteView.as_view()), name='delete_review'),
    # My reviews page.
    path('my_reviews/', login_required(views.MyReviewsListView.as_view()), name='my_reviews'),
    # Search results page.
    path('search/', views.SearchListView.as_view(), name='search'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    # admin urls
    path('admin/', admin.site.urls),
    # book_review urls
    path('', include('book_review.urls')),
    # users urls
    path('', include('users.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.views import serve
    from django.views.decorators.cache import never_cache
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # маршрут для обработки выгруженных файлов
else: # only for heroku , if deploy + nginx/apache need refactor
    from django.views.static import serve as serve
    urlpatterns.extend([
        url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
        url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),   
    ])
    

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(next_page='book_review:index'), name='logout'),
    path('register/', views.RegisterFormView.as_view(), name='register')
]

book_review/models.py
import datetime

from django.conf import settings
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

from .custom.constants import RATINGS


def get_sentinel_user():
    """
    If user is deleted replaces 'owner' field in Review model with 'deleted user' object.
    """
    return get_user_model().objects.get_or_create(username='deleted user')[0]


class Author(models.Model):
    """
    Book author model.
    """
    first_name = models.CharField(max_length=50)
    patronymic = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50)
    born = models.DateField(
        help_text='YYYY-MM-DD',
        validators=[MaxValueValidator(limit_value=datetime.date.today)]
    )

    class Meta:
        unique_together = ['first_name', 'patronymic', 'last_name', 'born']
        ordering = ['first_name']

    def __str__(self):
        """
        String representation is an author's full name.
        """
        parts = [self.first_name, self.last_name]
        if self.patronymic:
            parts.insert(1, self.patronymic)

        return " ".join(parts)


class Genre(models.Model):
    """
    Book genre model.
    """
    name = models.CharField(max_length=50, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Book(models.Model):
    """
    Book model.
    """
    title = models.CharField(max_length=100)
    original_title = models.CharField(max_length=100, blank=True)
    # Book might have multiple authors, so many-to-many relationship is used.
    authors = models.ManyToManyField(Author)
    genres = models.ManyToManyField(Genre)
    language = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    # Not limiting pub_date max value by today in case of anticipated books.
    pub_date = models.DateField(help_text='YYYY-MM-DD')
    description = models.TextField(max_length=1024, blank=True)
    full_img = models.ImageField(upload_to='img/book_img/full/', default='img/book_img/full/default-book-full.jpg')
    small_img = models.ImageField(upload_to='img/book_img/small/', default='img/book_img/small/default-book-small.jpg')
    pages = models.PositiveIntegerField(null=True, blank=True)
    slug = models.SlugField(max_length=80)

    class Meta:
        unique_together = ['title', 'pub_date']
        ordering = ['title']

    def is_published(self):
        """
        Returns True if book is already published.
        """
        return self.pub_date <= datetime.date.today()

    def get_absolute_url(self):
        # Using slug only is not safe enough since different books may have identical titles.
        # Using id only is not giving informative url for user,
        # So slug and id are used together.
        return reverse('book_review:book', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def __str__(self):
        return self.title


class Review(models.Model):
    """
    Review model.
    """
    title = models.CharField(max_length=60)
    # One review can only refer to one book.
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    text = models.TextField(max_length=8192)
    rating = models.IntegerField(choices=RATINGS)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET(get_sentinel_user)
    )
    pub_date = models.DateField(auto_now_add=True)

    class Meta:
        # Put unique constraint on book and owner fields,
        # since each user may only have 1 review on each book.
        unique_together = ['book', 'owner']

    def __str__(self):
        return self.title

book_review/forms.py
from django import forms


class SearchForm(forms.Form):
    """
    Sends data to SearchListView via GET method.
    """
    q = forms.CharField(max_length=50, label='', widget=forms.TextInput(attrs={
        'placeholder': 'Book, author, genre, year...',
        'class': 'form-control search-form',
    }),
                        )

book_review/views.py
import datetime
from itertools import chain

from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views import generic
from django.http import Http404
from urllib3 import HTTPResponse

from .models import Book, Review
from .custom.annotations import annotated_books
from .custom.search import search
from .forms import SearchForm
from .custom.constants import BOOKS_PER_PAGE, REVIEWS_PER_PAGE, SEARCH_CATEGORIES

# from django.http import HttpResponse # test plug


class IndexListView(generic.list.ListView):
    """
    Return list of anticipated books ordered by book publication date and title.
    """
    template_name = 'general/index.html'
    context_object_name = 'anticipated_books'
    paginate_by = BOOKS_PER_PAGE

    def get_queryset(self):
        today = datetime.date.today()
        anticipated_books = annotated_books.filter(pub_date__gt=today)
        return anticipated_books.order_by('pub_date', 'title')


class BooksListView(generic.list.ListView):
    """
    Return list of published books ordered according to provided url argument.
    'recent', 'popular' or 'best_rated' argument values are possible.
    Different argument value leads to 404.
    """
    template_name = 'books/books_list.html'
    context_object_name = 'books'
    paginate_by = BOOKS_PER_PAGE

    def get(self, *args, **kwargs):
        if self.request.GET.get('order') is None:
            return redirect(reverse('book_review:books_list') + '?order=recent')
        return super().get(*args, **kwargs)

    def get_queryset(self):
        today = datetime.date.today()
        published_books = annotated_books.filter(pub_date__lte=today)
        order_dict = {
            'recent': '-pub_date',
            'popular': '-num_reviews',
            'best_rated': '-avg_rating',
        }
        order_key = self.request.GET.get('order')
        order_value = order_dict.get(order_key)
        if order_value is None:
            raise Http404
        return published_books.order_by(order_value, 'title')


class BookDetailView(generic.detail.DetailView):
    """
    Return a particular book and list of reviews for it.
    Reviews are ordered by review publication date.
    Authenticated user who already has review on requested book
    will always see his review on the top of the list regardless of the date.
    """
    model = Book
    queryset = annotated_books
    query_pk_and_slug = True
    template_name = 'books/book_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = Review.objects.filter(book=context.get('book')).order_by('-pub_date')
        user = self.request.user if self.request.user.is_authenticated else None
        user_review = reviews.filter(owner=user).first()

        if user_review:
            other_reviews = reviews.exclude(owner=user)
            reviews = list(chain((user_review, ), other_reviews))

        paginator = Paginator(reviews, REVIEWS_PER_PAGE)
        page_number = self.request.GET.get('page', '1')
        page_obj = paginator.get_page(page_number)

        context.update({
            'paginator': paginator,
            'page_obj': page_obj,
            'is_paginated': True,
            'reviews': reviews,
        })
        return context


class ReviewCreateView(generic.edit.CreateView):
    """
    Create new review on a book.
    User may have at most one review for each book.
    If user already has review for requested book or book is not published yet,
    user will be redirected to book detail page.
    """
    model = Review
    fields = ['rating', 'title', 'text']
    template_name = 'reviews/add_review.html'

    def get(self, request, *args, **kwargs):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        book_reviews = book.review_set.all()
        users_already_reviewed = User.objects.filter(review__in=book_reviews)

        if not book.is_published() or request.user in users_already_reviewed:
            return redirect(book)

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book,
        })
        return context

    def form_valid(self, form):
        new_review = form.save(commit=False)
        new_review.owner = self.request.user
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        new_review.book = book
        return super().form_valid(form)

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()


class ReviewUpdateView(generic.edit.UpdateView):
    """
    Update authenticated user's review for a particular book.
    """
    fields = ['rating', 'title', 'text']
    template_name = 'reviews/edit_review.html'

    def get_object(self, queryset=None):
        # Get review by its book and owner fields since review.owner and review.book have unique_together constraint.
        # Benefit is a simple url without review id, for example, '/review/9-war-and-peace/edit/'.
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        review = get_object_or_404(Review, book=book, owner=self.request.user)
        return review

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book
        })
        return context


class ReviewDeleteView(generic.edit.DeleteView):
    """
    Delete authenticated user's review for a particular book.
    """
    template_name = 'reviews/delete_review.html'
    query_pk_and_slug = True

    def get_object(self, queryset=None):
        # Get review by its book and owner fields since review.owner and review.book have unique_together constraint.
        # Benefit is a simple url without review id, for example, '/review/9-war-and-peace/delete/'.
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        review = get_object_or_404(Review, book=book, owner=self.request.user)
        return review

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        context.update({
            'book': book
        })
        return context

    def get_success_url(self):
        book = get_object_or_404(Book, id=self.kwargs.get('pk'), slug=self.kwargs.get('slug'))
        return book.get_absolute_url()


class MyReviewsListView(generic.list.ListView):
    """
    Return a list of all reviews written by a user.
    Reviews are ordered by review publication date.
    """
    template_name = 'reviews/my_reviews.html'
    context_object_name = 'my_reviews'
    paginate_by = REVIEWS_PER_PAGE

    def get_queryset(self):
        return Review.objects.filter(owner=self.request.user).order_by('-pub_date', 'title')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SearchListView(generic.list.ListView):
    """
    Return a list of books found by request.
    'q' is a name of the variable that points to query string.
    """
    template_name = 'search/search.html'
    context_object_name = 'results'
    paginate_by = BOOKS_PER_PAGE

    def get(self, request, *args, **kwargs):
        form = SearchForm(data=request.GET)

        if form.is_valid():
            return super().get(request, *args, **kwargs)
        elif form.data.get('q') is None:
            return render(request, 'search/empty_search_request.html')
        else:
            return render(request, 'search/wrong_search_request.html')

    def get_queryset(self):
        q = self.request.GET.get('q')
        category = self.request.GET.get('category')
        results = search(q, category)
        return results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'q': self.request.GET.get('q'),
            'category': self.request.GET.get('category'),
            'SEARCH_CATEGORIES': SEARCH_CATEGORIES,
        })
        return context

book_review/templates/general/base.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport">
        <title>Book review</title>

        {% load static %}
        {% load custom_tags %}
        {% url 'users:login' as login_url %}
        {% url 'users:register' as register_url %}
        {% url 'book_review:my_reviews' as my_reviews_url %}
        {% url 'book_review:books_list' as books_list_url %}

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'custom/css/custom.css' %}">
        <link rel="shortcut icon" href="{% static 'custom/img/book.ico' %}" type="image/x-icon">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
        <script src="{% static 'custom/js/read_more.js' %}"></script>

    </head>
    <body class="d-flex flex-column min-vh-100">
        <a id="start"></a>

        <nav class="navbar navbar-expand-lg navbar-light bg-white border mb-4">
            <div class="container-fluid d-flex justify-content-lg-center">

                <div class="d-flex justify-content-end" style="min-width: 10.625rem;">
                    <a class="navbar-brand" href="{% url 'book_review:index' %}">
                        <img src="{% static 'custom/svg/book.svg' %}" alt="" width="30" height="30"><span class="ms-2">Book review</span></a>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".multi-collapse" aria-controls="el1 el2" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse multi-collapse" id="el1" style="max-width: 1140px;">

                    <form class="w-100 order-lg-last ms-2 mt-3 mt-lg-0" method="get" action="{% url 'book_review:search' %}">
                        <div class="input-group">
                            {{ search_form.q }}
                            <input type="hidden" name="category" value="any">
                            <button class="btn btn-color ms-1" type="submit">Search</button>
                        </div>
                    </form>

                    <ul class="navbar-nav ms-1 order-lg-first">
                        <li class="nav-item">
                            <a class="navigation-link text-nowrap ms-lg-0 {% if request.path == books_list_url and request.GET.order == 'recent' %}current-navigation-link{% endif %}" href="{% url 'book_review:books_list' %}?order=recent">Recent</a>
                        </li>
                        <li class="nav-item">
                            <a class="navigation-link text-nowrap {% if request.path == books_list_url and request.GET.order == 'popular' %}current-navigation-link{% endif %}" href="{% url 'book_review:books_list' %}?order=popular">Popular</a>
                        </li>
                        <li class="nav-item">
                            <a class="navigation-link text-nowrap {% if request.path == books_list_url and request.GET.order == 'best_rated' %}current-navigation-link{% endif %}" href="{% url 'book_review:books_list' %}?order=best_rated">Best rated</a>
                        </li>
                    </ul>

                </div>

                <div class="collapse navbar-collapse multi-collapse ms-1" id="el2" style="min-width: 10.625rem; flex-grow: 0;">
                    <ul class="navbar-nav ms-lg-2">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="navigation-link text-nowrap {% if request.path == my_reviews_url %}current-navigation-link{% endif %}" href="{{ my_reviews_url }}">Hello, {{user.username|title}}!</a>
                            </li>
                            <li class="nav-item">
                                <a class="navigation-link text-nowrap" href="{% url 'users:logout' %}{% url_next next=request.get_full_path %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="navigation-link text-nowrap {% if request.path == login_url %}current-navigation-link{% endif %}" href="{{ login_url }}{% url_next next=request.get_full_path %}">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="navigation-link text-nowrap {% if request.path == register_url %}current-navigation-link{% endif %}" href="{{ register_url }}{% url_next next=request.get_full_path %}">Sign up</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>


            </div>
        </nav>


        <div role="main" class="d-flex flex-column container flex-fill bg-white p-4" style="max-width: 1140px; border-radius: 0.5rem;">
            <div>
                {% block page_header %}{% endblock page_header %}
            </div>
            <div class="d-flex flex-fill flex-column">
                {% block content %} {% endblock content %}
            </div>
        </div>


        <footer class="container-fluid border bg-white mt-4">
            <div class="container border-bottom" style="max-width: 1140px; height: 1.5rem;"></div>
            <div class="container pb-4 pt-3 pt-md-1" style="max-width: 1140px;">

                <div class="row g-0">

                    <div class="d-flex align-items-center justify-content-center col-md order-0 order-md-1">
                        <ul class="d-flex mb-sm-0">
                            <li class="ms-2"><a class="footer-link" href="#">Terms</a></li>
                            <li><a class="footer-link" href="#">Privacy</a></li>
                            <li><a class="footer-link" href="#">About us</a></li>
                            <li class="me-2"><a class="footer-link" href="#">Help</a></li>
                        </ul>
                    </div>

                    <div class="d-flex align-items-center justify-content-center justify-content-sm-start justify-content-md-end col-sm order-sm-2">
                        <ul class="d-flex m-0">
                            <li class="ms-2"><a class="footer-icon-link facebook" href="#"><i class="fab fa-facebook"></i></a></li>
                            <li class="ms-3"><a class="footer-icon-link instagram" href="#">
                                <i class="fab fa-instagram"></i>
                            </a></li>
                            <li class="ms-3"><a class="footer-icon-link telegram" href="#"><i class="fab fa-telegram"></i></a></li>
                            <li class="ms-3"><a class="footer-icon-link linkedin" href="#"><i class="fab fa-linkedin"></i></a></li>
                            <li class="ms-3"><a class="footer-icon-link twitter" href="#"><i class="fab fa-twitter"></i></a></li>
                        </ul>
                    </div>

                    <div class="col-sm d-flex justify-content-center justify-content-sm-end justify-content-md-start order-sm-1 order-md-0">

                        <a class="d-flex align-items-center footer-logo-link me-2 me-md-0" href="#start">
                            <i class="icon-book mt-2 me-1" style="font-size: 1.875rem;"></i>
                            <span>Book review<i class="far fa-copyright ms-1 me-1"></i>2022</span>
                        </a>

                    </div>

                </div>
            </div>
        </footer>

    </body>
</html>

book_review/templates/general/index.html
{%  extends 'general/base.html' %}
{% load static %}

{% block page_header %}
    <div class="mb-3">
        <h1>Welcome to the Book Review!</h1>
    </div>

    <div class="row g-0 mb-5">
        <div class="col-md order-md-1 mb-3 mb-md-0">
            <img src="{% static 'custom/img/main.png' %}" class="img-fluid" alt="">
        </div>
        <div class="col-md-4 col-lg-5 order-md-0">
            <div class="d-block d-md-none d-lg-block">
                <p>Look for your favorite books and rate them.</p>
                <p>Track your reviews and edit or delete them anytime.</p>
                <p>Check out other people's ratings and reviews.</p>
                <p>See the books lists such as recent, the most popular and the best rated books.</p>
                <p>Keep an eye on the most anticipated books.</p>
            </div>
            <div class="d-none d-md-block d-lg-none">
                <ul>
                    <li>Look for interesting books and rate them.</li>
                    <li>Track your reviews and edit or delete them anytime.</li>
                    <li>Check out other people's ratings and reviews.</li>
                    <li>See the books lists such as recent, the most popular and the best rated books.</li>
                    <li>Keep an eye on the most anticipated books.</li>
                </ul>
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'book_review:my_reviews' %}" class="btn btn-color">My reviews >></a>
            {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-color">Get started!</a>
            {% endif %}
        </div>

    </div>
{% endblock page_header %}

{% block content %}


    {% if paginator.count %}
        <div class="pb-1 mb-4 border-bottom">
            <h2>Most anticipated books</h2>
        </div>
        <ul>
            {% for book in anticipated_books %}

                <li>{% include 'books/book_card.html' %}</li>

            {% endfor %}
        </ul>

        {% include 'general/pagination.html' %}

    {% else %}

        <h4>No books are anticipated at the moment.</h4>

    {% endif %}


{% endblock content %}

book_review/templates/general/pagination.html
{% if paginator.num_pages > 1 %}
    {% load custom_tags %}
    {% get_page_range as page_range %}

    <div class="d-flex align-items-center justify-content-between mt-auto" style="font-size: 1.125rem;">

        <div>
            {% if page_obj.has_previous %}
                <a class="pagination-item pagination-arrow-link" href="?{% url_replace page=page_obj.previous_page_number %}">
                    <span class="me-1"><i class="fas fa-chevron-left" style="font-size: 0.875rem;"></i></span>
                    <span class="d-none d-sm-inline">Previous page</span>
                </a>
            {% else %}
                <span class="pagination-item text-muted">
                    <span class="me-1"><i class="fas fa-chevron-left" style="font-size: 0.875rem;"></i></span>
                    <span class="d-none d-sm-inline">Previous page</span>
                </span>
            {% endif %}
        </div>

        <ul class="d-flex m-0" style="font-size: 1rem; padding-bottom: 0.125rem;">
            {% for page_num in page_range %}
                <li class="mx-1" style="min-width: 1.625rem;">
                    {% if page_num == page_obj.number %}
                        <span class="pagination-item current-pagination">{{ page_num }}</span>
                    {% else %}
                        {% if page_num == page_obj.paginator.ELLIPSIS %}
                            <span class="pagination-item pagination-ellipsis">{{ page_num }}</span>
                        {% else %}
                            <a class="pagination-item pagination-number-link" href="?{% url_replace page=page_num %}">{{ page_num }}</a>
                        {% endif %}
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        <div>
            {% if page_obj.has_next %}
                <a class="pagination-item pagination-arrow-link" href="?{% url_replace page=page_obj.next_page_number %}">
                    <span class="d-none d-sm-inline">Next page</span>
                    <span class="ms-1"><i class="fas fa-chevron-right" style="font-size: 0.875rem;"></i></span>
                </a>
            {% else %}
                <span class="pagination-item text-muted">
                    <span class="d-none d-sm-inline">Next page</span>
                    <span class="ms-1"><i class="fas fa-chevron-right" style="font-size: 0.875rem;"></i></span>
                </span>
            {% endif %}
        </div>
    </div>
{% endif %}